#!/bin/bash
echo ""
echo ">>>>>SSH Internet Solution<<<<<"
echo ""
echo "-------------------------------"
echo "USERNAME          EXP DATE     "
echo "-------------------------------"
while read akunexpire
do
        AKUN="$(echo $akunexpire | cut -d: -f1)"
        ID="$(echo $akunexpire | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge 1000 ]]; then
        printf "%-17s %2s\n" "$AKUN" "$exp"
        fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo "-------------------------------"
echo "Jumlah akun: $JUMLAH user"
echo "-------------------------------"
