#!/bin/bash
m=$(echo "30 * $2" | bc)
passwd -u $1
usermod $1 -e `date -d "$m days" +"%Y-%m-%d"`
exp="$(chage -l $1 | grep "Account expires" | awk -F": " '{print $2}')"
echo "Username $1 berhasil diperpanjang"
echo "Aktif sampai $exp"